Snowfork/polkadot-sdk

Cargo.lock
cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/assets/common/src/matching.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/snowbridge_outbound_queue.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs

Merge in outbound queue refactor from snowbridge.

Merge from Snowbridge

---

cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/assets/common/src/matching.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs

Resolves: SNO-735
Snowfork companion: https://github.com/Snowfork/snowbridge/pull/986

Remove gateway contract locations from Assets

---

Cargo.lock
cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-rococo/Cargo.toml
cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-rococo/src/tests/snowbridge.rs

✄ -----------------------------------------------------------------------------
Thank you for your Pull Request! 🙏 Please make sure it follows the contribution guidelines outlined in
[this document](https://github.com/paritytech/polkadot-sdk/blob/master/docs/CONTRIBUTING.md) and fill
out the sections below. Once you're ready to submit your PR for review, please
delete this section and leave only the text under the "Description" heading.
*Please include a summary of the changes and the related issue. Please also include relevant motivation and context,
including:*
- What does this PR do?
- Why are these changes needed?
- How were these changes implemented and what do they affect?
*Use [Github semantic
linking](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-r …

xcm integration test

---

cumulus/parachains/common/src/snowbridge_config.rs

Fixes the transfer token fee on Rococo and adds fee config for KSM and DOT.
Snowbridge companion: https://github.com/Snowfork/snowbridge/pull/996

Fix assethub fee

---

Cargo.lock
cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
cumulus/parachains/integration-tests/emulated/networks/rococo-wococo-system/Cargo.toml
cumulus/parachains/integration-tests/emulated/networks/rococo-wococo-system/src/lib.rs
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/testing/penpal/Cargo.toml
cumulus/parachains/runtimes/testing/penpal/src/lib.rs
cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
cumulus/polkadot-parachain/src/command.rs

Resolves: SNO-708
Snowbridge companion: https://github.com/Snowfork/snowbridge/pull/1012

Asset transfer to penpal

---

cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-wococo/src/lib.rs
cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/lib.rs
cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-wococo/src/lib.rs
cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
cumulus/xcm/xcm-emulator/src/lib.rs

Resolves: SNO-763
Snowbrigde Companion: https://github.com/Snowfork/snowbridge/pull/1018

Parameterize message origin in Tests

---

Cargo.lock
cumulus/pallets/xcmp-queue/src/tests.rs
polkadot/runtime/parachains/src/ump_tests.rs
substrate/frame/message-queue/Cargo.toml
substrate/frame/message-queue/src/benchmarking.rs
substrate/frame/message-queue/src/integration_test.rs
substrate/frame/message-queue/src/lib.rs
substrate/frame/message-queue/src/mock.rs
substrate/frame/message-queue/src/mock_helpers.rs
substrate/frame/message-queue/src/tests.rs
substrate/frame/support/src/traits/messages.rs

Fix for https://github.com/paritytech/polkadot-sdk/issues/2319

Message queue reentrancy issue fix

---

Cargo.lock
cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/Cargo.toml
cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/lib.rs
cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/Cargo.toml
cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/lib.rs
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
cumulus/parachains/runtimes/bridge-hubs/common/src/message_queue.rs
cumulus/primitives/core/src/lib.rs
cumulus/xcm/xcm-emulator/src/lib.rs

✄ -----------------------------------------------------------------------------
Thank you for your Pull Request! 🙏 Please make sure it follows the contribution guidelines outlined in
[this document](https://github.com/paritytech/polkadot-sdk/blob/master/docs/CONTRIBUTING.md) and fill
out the sections below. Once you're ready to submit your PR for review, please
delete this section and leave only the text under the "Description" heading.
*Please include a summary of the changes and the related issue. Please also include relevant motivation and context,
including:*
- What does this PR do?
- Why are these changes needed?
- How were these changes implemented and what do they affect?
*Use [Github semantic
linking](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-r …

Fix compile error & breaking tests

---

cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs

Snowbridge companion: https://github.com/Snowfork/snowbridge/pull/1026

Updates pallet indices

---

Cargo.lock
cumulus/parachain-template/node/src/chain_spec.rs
cumulus/parachain-template/pallets/template/Cargo.toml
cumulus/parachain-template/pallets/template/src/lib.rs

Reverts changes Snowfork made to the template parachain.

Revert template parachain changes

---

cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs

Fixes `create_agent` and `create_channel` tests by updating the pallet indices.

Updates pallet indices in integration tests

---

cumulus/parachains/common/src/lib.rs

Should have been part of https://github.com/Snowfork/polkadot-sdk/pull/41.

Remove old mod

---

cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs

Resolves: [SNO-772](https://linear.app/snowfork/issue/SNO-772)

Benchmark fixes

---

Cargo.lock
Cargo.toml
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/assets/common/src/matching.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_ethereum_config.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/testing/penpal/Cargo.toml
cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs

Fixes related to https://github.com/paritytech/polkadot-sdk/pull/2522.
Addressed all comments in the upstream PR. These applied will be to https://github.com/Snowfork/polkadot-sdk/tree/merge-to-upstream.

Fixes related to pr comments

---

cumulus/polkadot-parachain/Cargo.toml

The beacon mainnet spec should be the default spec, and then we'll specify `--no-default-features` when building the bridge for testnet cases.
Snowbridge companion: https://github.com/Snowfork/snowbridge/pull/1045

Set beacon mainnet spec as default

---

Cargo.lock
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs

Snowbridge companion: https://github.com/Snowfork/snowbridge/pull/1054

Save gateway address in storage

---

cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs

Snowbridge: https://github.com/Snowfork/snowbridge/pull/1060

Make base fee configurable from storage

---

cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs

Snowbridge sdk: https://github.com/Snowfork/snowbridge/pull/1069

Remove explicit Snowbridge teleports

---

Cargo.lock
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs

Fixes for:
- https://github.com/paritytech/polkadot-sdk/pull/2522#discussion_r1427683824
- https://github.com/paritytech/polkadot-sdk/pull/2522#discussion_r1427750290

Runtime config cleanup

---

cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/assets/common/src/matching.rs

Snowbridge: https://github.com/Snowfork/snowbridge/pull/1075

Use FromNetwork

---

cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_ethereum_config.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/bridge-hubs/common/src/message_queue.rs

Snowbridge: https://github.com/Snowfork/snowbridge/pull/1076

Misc documentation and comment updates

---

cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs

Resolves: [SNO-796](https://linear.app/snowfork/issue/SNO-796)
https://github.com/paritytech/polkadot-sdk/pull/2522#discussion_r1432316512

Adds message queue service weight comment

---

cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs

Adds comments for the Snowbridge emulated tests.
Snowbridge companion: https://github.com/Snowfork/snowbridge/pull/1110

Adds emulated test comments

---

cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs

Snowbridge companion: https://github.com/Snowfork/snowbridge/pull/1119

Remove minimal spec

---

cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
cumulus/parachains/runtimes/test-utils/src/test_cases.rs

In the event we need to re-initialize our test, we will need to reset our nonces to zero. This will allow this to happen in Rococo.
Snowbridge Companion: https://github.com/Snowfork/snowbridge/pull/1128
Resolves: [SNO-836](https://linear.app/snowfork/issue/SNO-836)

Reset Nonces in Rococo

---

bridges/snowbridge/pallets/ethereum-client/src/config/mod.rs
bridges/snowbridge/pallets/ethereum-client/src/lib.rs
bridges/snowbridge/pallets/ethereum-client/src/tests.rs

Resolves: [SNO-912](https://linear.app/snowfork/issue/SNO-912)
This is just on the on-chain part, off-chain coming soon.

Adds finalized header gap check

---

bridges/snowbridge/pallets/inbound-queue/src/mock.rs
bridges/snowbridge/pallets/outbound-queue/runtime-api/src/lib.rs
bridges/snowbridge/pallets/outbound-queue/src/api.rs
bridges/snowbridge/pallets/outbound-queue/src/lib.rs
bridges/snowbridge/pallets/outbound-queue/src/mock.rs
bridges/snowbridge/pallets/outbound-queue/src/test.rs
bridges/snowbridge/pallets/system/src/lib.rs
bridges/snowbridge/pallets/system/src/mock.rs
bridges/snowbridge/primitives/core/src/outbound.rs
bridges/snowbridge/primitives/core/src/pricing.rs
cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs

Bridging fees are calculated using a static ETH/DOT exchange rate that can deviate significantly from the real-world exchange rate. We therefore need to add a safety margin to the fee so that users almost aways cover the cost of relaying.
> Why introduce a `multiplier` parameter instead of configuring an exchange rate which already has a safety factor applied?
When converting from ETH to DOT, we need to _divide_ the multiplier by the exchange rate, and to convert from DOT to ETH we need to _multiply_ the multiplier by the exchange rate.
> Other input parameters to the fee calculation can also deviate from real-world values. These include substrate weights, gas prices, and so on. Why does the multiplier introduced here not adjust those?
A single scalar multiplier won't be able to …

Add a linear fee multiplier to ensure safety margins

---

bridges/snowbridge/pallets/ethereum-client/src/lib.rs
bridges/snowbridge/pallets/ethereum-client/src/tests.rs

This change corrects the bug where importing a finalized header in the next sync committee period, without the next sync committee, prevents any subsequent sync committee updates.
Light client period: `1`
Import header in period `2` (because next sync committee is already known)
Light client period should now be `2`, but it is still `1`.
Current and next sync committee now references the wrong periods, and every subsequent sync committee imports fails because of this check: https://github.com/Snowfork/polkadot-sdk/blob/snowbridge/bridges/snowbridge/pallets/ethereum-client/src/lib.rs#L384
A detailed description of the issue here: https://www.notion.so/snowfork/Prod-Investigation-45a74b16488d44249de26f149dbc3ad1
Resolves: [SNO-981](https://linear.app/snowfork/issue/SNO-981)

Reject finalized updates without a sync committee in next store period

---

cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs

Method was removed downstream and still used upstream. 
Fixes: https://github.com/Snowfork/polkadot-sdk/actions/runs/9309316231/job/25624788118

Fix integration tests

---

bridges/snowbridge/pallets/ethereum-client/src/impls.rs

Fixes two audit issues:
3. Inefficiency in verify_execution_proof function
5. Outdated comment

Audit fixes

---

bridges/snowbridge/primitives/router/src/inbound/mod.rs

Snowbridge: https://github.com/Snowfork/snowbridge/pull/1284

Remove destination parachain transfer
